---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - Liam Wall
thanks: "Code and data are available at: LINK."
date: 27 September 2024
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```


# Introduction

You can and should cross-reference sections and sub-sections. We use @citeR.

The remainder of this paper is structured as follows. 



# Data

The data used to produce this paper was made available by Open Data Toronto through their R library 'opendatatoronto' (@opendatatoronto). All actions to the data for the sake of this paper was used on the open source programming language R (@citeR). Specifically the data cleaning, simulation, and testing was made possible by the libraries 'tidyverse' (@tidyverse), 'janitor' (@janitor), 'dplyr' (@dplyr), 'lubridate' for dates (@lubridate), and 'testthat' for the tests  of the simulation and real data sets (@testthat). All graphs and tables throughout this paper were produced using the library 'ggplot2' (@ggplot2).


# Results


# Discussion

## Limitations

Weaknesses and next steps should also be included.


\newpage


# References


